sudo: required

language: python
python:
  - "3.6.4"

services:
  - docker

install:
  - docker build . -t infrastructureplayground/django:latest
  - docker network create backend_network
  - docker run -d unnotech/postgres-replication:10.4 --name=postgres --network=backend_network
  - docker run -d infrastructureplayground/django:latest --name=django --network=backend_network
  - docker exec -it django bash

jobs:
  include:
    - stage: Authentication Unit Testing
      script: python manage.py test authentication.tests.RegistrationTest
      script: python manage.py test authentication.tests.LoginTest
    - stage: Book Inventory Unit Testing
      script: python manage.py test inventory.tests.BooksTest.test_list_books
      script: python manage.py test inventory.tests.BooksTest.test_create_book
      script: python manage.py test inventory.tests.BooksTest.test_get_book
      script: python manage.py test inventory.tests.BooksTest.test_update_book
      script: python manage.py test inventory.tests.BooksTest.test_delete_book