version: '2'

services:
  django:
    build:
      image: infrastructureplayground/django:latest
      dockerfile: Dockerfile
      entrypoint: codeship-entrypoint.sh
  postgres:
    image: unnotech/postgres-replication:10.4

# Helpful Resources:
# - https://documentation.codeship.com/pro/builds-and-configuration/services/