version: 2
jobs:
  build:
    parallelism: 4
    docker:
      - image: infrastructureplayground/django:latest
        name: django
        environment:
          POSTGRES_USER: playground
          POSTGRES_PASSWORD: playground
          POSTGRES_DB: playground
          POSTGRES_PORT: 5432
          POSTGRES_SERVICE: postgres
          DOCKERIZED: true
          TZ: Asia/Singapore
      - image: unnotech/postgres-replication:10.4
          name: postgres
          environment:
            POSTGRES_USER: playground
            POSTGRES_PASSWORD: playground
            POSTGRES_DB: playground
            POSTGRES_PORT: 5432
            POSTGRES_SERVICE: postgres
            TZ: Asia/Singapore
    steps:
      - checkout
      - run: python manage.py test authentication.tests.RegistrationTest
      - run: python manage.py test authentication.tests.LoginTest
      - run: python manage.py test inventory.tests.BooksTest

workflows:
  version: 2
  pipeline:
    jobs:
      - build
